list: $/acornassociated/messaging/models/message/columns.yaml
modelClass: Acornassociated\Messaging\Models\Message
title: Messaging
noRecordsMessage: 'backend::lang.list.no_records'
showSetup: true
showCheckboxes: true
recordsPerPage: 20
toolbar:
    buttons: list_toolbar
    search:
        prompt: 'backend::lang.list.search_prompt'
recordUrl: 'acornassociated/messaging/messaging/update/:id'
