list: $/acornassociated/messaging/models/state/columns.yaml
modelClass: Acornassociated\Messaging\Models\State
title: State
noRecordsMessage: 'backend::lang.list.no_records'
showSetup: true
showCheckboxes: true
recordsPerPage: 20
toolbar:
    buttons: list_toolbar
    search:
        prompt: 'backend::lang.list.search_prompt'
recordUrl: 'acornassociated/messaging/state/update/:id'
